spring.application.name=fastpass
spring.datasource.url=jdbc:postgresql://localhost:5432/fastpass
spring.datasource.username=fastpass
spring.datasource.password=fastpass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
